name: Releasing packages

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  packaging-release-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      PKNAME: rime-daagornt
      BASE: base
      EXTN: extension
    steps:
      - name: Checkout base
        uses: actions/checkout@v5
      
      - name: Prepare directories
        run: |
          cd ${GITHUB_WORKSPACE}
          mkdir -p ${BASE}
          mkdir -p ${EXTN}

      - name: Copy README.md & LICENSE
        run: |
          cd ${GITHUB_WORKSPACE}
          cp ./README.md ./$BASE/README.md
          cp ./LICENSE ./$BASE/LICENSE
          cp ./README.md ./$EXTN/README.md
          cp ./LICENSE ./$EXTN/LICENSE
      
      - name: Copy base files
        run: |
          cd ${GITHUB_WORKSPACE}
          cp -rf ./dictionary ./${BASE}/
          cp -rf ./opencc ./${BASE}/
          cp -rf ./core/customize ./${BASE}/
          cp -rf ./core/daagornt.lib.* ./${BASE}/
          cp -rf ./icon/daagornt.icon.* ./${BASE}/
          cp -f ./lang-*/daagornt.lib.* ./${BASE}/
          cp -f ./lang-*/daagornt.rscm.* ./${BASE}/
          cp -f ./lang-*/README-* ./${BASE}/
          ls -al ./${BASE}/
      
      - name: Copy extension files
        run: |
          cd ${GITHUB_WORKSPACE}
          cp -rf ./core/experience ./${EXTN}/
          cp -rf ./supplimental ./${EXTN}/
          cp -rf ./patch ./${EXTN}/
          ls -al ./${EXTN}/
      
      - name: Create ZIP package
        if: github.event_name == 'release'
        shell: bash
        run: |
          cd ${GITHUB_WORKSPACE}
          pushd $BASE || exit 1
          zip -9vr ../${PKNAME}-${BASE}.zip .
          popd || exit 1
          pushd $EXTN || exit 1
          zip -9vr ../${PKNAME}-${EXTN}.zip .
          popd || exit 1
        
      - name: Upload base files to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PKNAME }}-${{ env.BASE }}
          path: |
            ./${{ env.BASE }}/*
        
      - name: Upload extension files to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PKNAME }}-${{ env.EXTN }}
          path: |
            ./${{ env.EXTN }}/*

      - name: Upload base to release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./${{ env.PKNAME }}-${{ env.BASE }}.*
          tag: ${{ github.ref }}
          file_glob: true

      - name: Upload extension to release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./${{ env.PKNAME }}-${{ env.EXTN }}.*
          tag: ${{ github.ref }}
          file_glob: true
